**1. Carregando o conjunto de dados**

In [207]:
import pandas as pd

df_chamados = pd.read_csv("chamados.csv")

df_original = df_chamados.copy()

**1.2 Dimensões do dataset**

In [208]:
df_chamados.shape

(5000, 44)

**1.3 Visualização dos dados**

In [209]:
df_chamados.head()

,ticket_id,created_at,customer_id,department,city_x,state_x,device_type,os,browser,network_type,...,vip,monthly_revenue,num_events,last_event_date,event_types,num_abertura,num_updates,num_encerramento,num_images_y,target_category
0,1,2025-01-01T00:17:00,5012,Operações,Campinas,BA,Desktop,Windows,Safari,WiFi,...,NaN,NaN,0,NaN,NaN,0,0,0,NaN,Hardware
1,2,2025-01-01T00:34:00,6574,Financeiro,Campinas,RJ,Notebook,Windows,Chrome,5G,...,NaN,NaN,0,NaN,NaN,0,0,0,NaN,RH
2,3,2025-01-01T00:51:00,2139,TI,Campinas,MG,Desktop,Linux,Chrome,5G,...,NaN,NaN,0,NaN,NaN,0,0,0,NaN,Financeiro
3,4,2025-01-01T01:08:00,7216,Financeiro,Belo Horizonte,RJ,Mobile,Android,Chrome,Cabo,...,NaN,NaN,0,NaN,NaN,0,0,0,NaN,Software
4,5,2025-01-01T01:25:00,5040,Financeiro,Belo Horizonte,PR,Mobile,iOS,Edge,Cabo,...,NaN,NaN,0,NaN,NaN,0,0,0,NaN,Rede

**2. Limpeza dos dados**

**2.1 Remoção das colunas sem dados**

In [210]:
percentual_nulos = df_chamados.isna().mean()

colunas_vazias = percentual_nulos[percentual_nulos >= 0.99].index

print("Colunas com 99% ou mais de valores ausentes:")
print(colunas_vazias)

df_chamados = df_chamados.drop(columns=colunas_vazias)

print("\nColunas removidas:")
print(colunas_vazias)

Colunas com 99% ou mais de valores ausentes:
Index(['company', 'segment', 'employees', 'city_y', 'state_y', 'contract_type',
       'customer_since', 'vip', 'monthly_revenue', 'last_event_date',
       'event_types', 'num_images_y'],
      dtype='object')

Colunas removidas:
Index(['company', 'segment', 'employees', 'city_y', 'state_y', 'contract_type',
       'customer_since', 'vip', 'monthly_revenue', 'last_event_date',
       'event_types', 'num_images_y'],
      dtype='object')

**2.2 - Remoção de Colunas sem Variabilidade**

In [211]:
colunas_sem_variacao = df_chamados.columns[df_chamados.nunique() <= 1]

print("Colunas sem variabilidade:")
print(colunas_sem_variacao)

Colunas sem variabilidade:
Index(['num_events', 'num_abertura', 'num_updates', 'num_encerramento'], dtype='object')

In [212]:
df_chamados = df_chamados.drop(columns=colunas_sem_variacao)

**2.3 Verificação de valores ausentes**

In [213]:
df_chamados.isna().sum().sort_values(ascending=False)

ticket_id                0
created_at               0
customer_id              0
department               0
city_x                   0
state_x                  0
device_type              0
os                       0
browser                  0
network_type             0
historical_tickets       0
sla_hours                0
resolution_time_hours    0
title                    0
description              0
image_path               0
image_width              0
image_height             0
priority                 0
status                   0
assigned_team            0
has_attachment           0
sentiment_score          0
num_words                0
num_images_x             0
latitude                 0
longitude                0
target_category          0
dtype: int64

**2.4 Identificação das variáveis**

In [214]:
df_chamados.columns

Index(['ticket_id', 'created_at', 'customer_id', 'department', 'city_x',
       'state_x', 'device_type', 'os', 'browser', 'network_type',
       'historical_tickets', 'sla_hours', 'resolution_time_hours', 'title',
       'description', 'image_path', 'image_width', 'image_height', 'priority',
       'status', 'assigned_team', 'has_attachment', 'sentiment_score',
       'num_words', 'num_images_x', 'latitude', 'longitude',
       'target_category'],
      dtype='object')

**2.5 Verificar valores duplicados**

In [215]:
df_chamados.duplicated().sum()

np.int64(0)

**2.6 Verificação de consistência das categorias**

In [216]:
for coluna in colunas_categoricas:
    print(f"\n{coluna}:")
    print(df_chamados[coluna].value_counts())

department:
department
RH            1274
TI            1273
Operações     1229
Financeiro    1224
Name: count, dtype: int64

city_x:
city_x
Santos            1012
Belo Horizonte    1008
Campinas          1002
Curitiba          1000
São Paulo          978
Name: count, dtype: int64

state_x:
state_x
RS    862
SP    849
BA    837
MG    834
RJ    822
PR    796
Name: count, dtype: int64

device_type:
device_type
Desktop     1684
Mobile      1683
Notebook    1633
Name: count, dtype: int64

os:
os
Windows    1256
Android    1252
Linux      1248
iOS        1244
Name: count, dtype: int64

browser:
browser
Safari     1302
Edge       1243
Firefox    1235
Chrome     1220
Name: count, dtype: int64

network_type:
network_type
Cabo    1296
4G      1249
5G      1231
WiFi    1224
Name: count, dtype: int64

priority:
priority
Crítica    1277
Baixa      1260
Média      1248
Alta       1215
Name: count, dtype: int64

status:
status
Aberto          1689
Fechado         1657
Em andamento    1654
Name: count, dtype: int64

assigned_team:
assigned_team
Aplicações    1288
Infra         1247
N1            1243
N2            1222
Name: count, dtype: int64

In [217]:
colunas_categoricas = [
    'department',
    'city_x',
    'state_x',
    'device_type',
    'os',
    'browser',
    'network_type',
    'priority',
    'status',
    'assigned_team'
]

print(colunas_categoricas)

['department', 'city_x', 'state_x', 'device_type', 'os', 'browser', 'network_type', 'priority', 'status', 'assigned_team']

**2.7 Transformação das variáveis categóricas**

In [218]:
for coluna in colunas_categoricas:
    print(f"\n{coluna}:")
    print(df_chamados[coluna].unique())

department:
['Operações' 'Financeiro' 'TI' 'RH']

city_x:
['Campinas' 'Belo Horizonte' 'Santos' 'São Paulo' 'Curitiba']

state_x:
['BA' 'RJ' 'MG' 'PR' 'RS' 'SP']

device_type:
['Desktop' 'Notebook' 'Mobile']

os:
['Windows' 'Linux' 'Android' 'iOS']

browser:
['Safari' 'Chrome' 'Edge' 'Firefox']

network_type:
['WiFi' '5G' 'Cabo' '4G']

priority:
['Alta' 'Crítica' 'Média' 'Baixa']

status:
['Fechado' 'Em andamento' 'Aberto']

assigned_team:
['N2' 'Aplicações' 'Infra' 'N1']

In [219]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [220]:
dados_categoricos = encoder.fit_transform(
    df_chamados[colunas_categoricas]
)

dados_categoricos

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [221]:
colunas_codificadas = encoder.get_feature_names_out(colunas_categoricas)

print(colunas_codificadas)

['department_Financeiro' 'department_Operações' 'department_RH'
 'department_TI' 'city_x_Belo Horizonte' 'city_x_Campinas'
 'city_x_Curitiba' 'city_x_Santos' 'city_x_São Paulo' 'state_x_BA'
 'state_x_MG' 'state_x_PR' 'state_x_RJ' 'state_x_RS' 'state_x_SP'
 'device_type_Desktop' 'device_type_Mobile' 'device_type_Notebook'
 'os_Android' 'os_Linux' 'os_Windows' 'os_iOS' 'browser_Chrome'
 'browser_Edge' 'browser_Firefox' 'browser_Safari' 'network_type_4G'
 'network_type_5G' 'network_type_Cabo' 'network_type_WiFi' 'priority_Alta'
 'priority_Baixa' 'priority_Crítica' 'priority_Média' 'status_Aberto'
 'status_Em andamento' 'status_Fechado' 'assigned_team_Aplicações'
 'assigned_team_Infra' 'assigned_team_N1' 'assigned_team_N2']

In [222]:
df_categoricas = pd.DataFrame(
    dados_categoricos,
    columns=colunas_codificadas
)

df_categoricas.head()

,department_Financeiro,department_Operações,department_RH,department_TI,city_x_Belo Horizonte,city_x_Campinas,city_x_Curitiba,city_x_Santos,city_x_São Paulo,state_x_BA,...,priority_Baixa,priority_Crítica,priority_Média,status_Aberto,status_Em andamento,status_Fechado,assigned_team_Aplicações,assigned_team_Infra,assigned_team_N1,assigned_team_N2
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

In [223]:
df_chamados.columns

Index(['ticket_id', 'created_at', 'customer_id', 'department', 'city_x',
       'state_x', 'device_type', 'os', 'browser', 'network_type',
       'historical_tickets', 'sla_hours', 'resolution_time_hours', 'title',
       'description', 'image_path', 'image_width', 'image_height', 'priority',
       'status', 'assigned_team', 'has_attachment', 'sentiment_score',
       'num_words', 'num_images_x', 'latitude', 'longitude',
       'target_category'],
      dtype='object')

**2.8 Preparação das variáveis numéricas**

In [224]:
colunas_numericas = [
    'historical_tickets',
    'sla_hours',
    'resolution_time_hours',
    'image_width',
    'image_height',
    'sentiment_score',
    'num_words',
    'num_images_x',
    'latitude',
    'longitude'
]

print(colunas_numericas)

['historical_tickets', 'sla_hours', 'resolution_time_hours', 'image_width', 'image_height', 'sentiment_score', 'num_words', 'num_images_x', 'latitude', 'longitude']

In [225]:
df_chamados[colunas_numericas].isna().sum()

historical_tickets       0
sla_hours                0
resolution_time_hours    0
image_width              0
image_height             0
sentiment_score          0
num_words                0
num_images_x             0
latitude                 0
longitude                0
dtype: int64

In [226]:
df_chamados[colunas_numericas].describe()

,historical_tickets,sla_hours,resolution_time_hours,image_width,image_height,sentiment_score,num_words,num_images_x,latitude,longitude
count,5000.000000,5000.000000,5000.00000,5000.00000,5000.000000,5000.00000,5000.00000,5000.000000,5000.000000,5000.000000
mean,19.933600,19.135200,36.02900,553.29060,371.952000,-0.00319,5.25460,1.506200,-28.355553,-48.097434
std,11.827813,15.809355,20.82298,111.36053,79.284335,0.58097,1.18628,1.130406,3.112418,2.857408
min,0.000000,4.000000,1.00000,191.00000,165.000000,-1.00000,3.00000,0.000000,-33.798845,-53.099397
25%,10.000000,8.000000,18.00000,500.00000,333.000000,-0.51625,5.00000,0.000000,-31.042769,-50.514807
50%,20.000000,12.000000,36.00000,500.00000,342.000000,0.00500,5.00000,2.000000,-28.367316,-48.104285
75%,30.000000,24.000000,54.00000,612.00000,408.000000,0.50600,6.00000,3.000000,-25.666005,-45.638371
max,40.000000,48.000000,72.00000,738.00000,750.000000,1.00000,7.00000,3.000000,-22.904986,-43.201069

In [227]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [228]:
dados_numericos = scaler.fit_transform(
    df_chamados[colunas_numericas]
)

In [229]:
df_numericas = pd.DataFrame(
    dados_numericos,
    columns=colunas_numericas
)

df_numericas.head()

,historical_tickets,sla_hours,resolution_time_hours,image_width,image_height,sentiment_score,num_words,num_images_x,latitude,longitude
0,-1.600929,-0.957453,-0.385622,-0.478589,0.038448,-0.956788,0.628414,0.436878,1.085549,-1.728392
1,-1.178155,-0.451373,0.430865,0.527254,0.454713,1.633965,0.628414,1.321605,-1.473447,-0.735041
2,-0.248050,0.307747,0.526923,1.658827,0.530397,0.700949,0.628414,-1.332575,0.384010,-1.157911
3,-1.516374,-0.451373,0.767066,0.527254,-0.352589,0.540856,-1.900753,1.321605,1.349118,0.476587
4,-1.009045,1.825988,1.343410,-0.478589,-0.491344,1.010807,0.628414,1.321605,0.339452,-0.417682

In [230]:
dados_processados = pd.concat(
    [df_numericas, df_categoricas],
    axis=1
)

dados_processados.head()

,historical_tickets,sla_hours,resolution_time_hours,image_width,image_height,sentiment_score,num_words,num_images_x,latitude,longitude,...,priority_Baixa,priority_Crítica,priority_Média,status_Aberto,status_Em andamento,status_Fechado,assigned_team_Aplicações,assigned_team_Infra,assigned_team_N1,assigned_team_N2
0,-1.600929,-0.957453,-0.385622,-0.478589,0.038448,-0.956788,0.628414,0.436878,1.085549,-1.728392,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,-1.178155,-0.451373,0.430865,0.527254,0.454713,1.633965,0.628414,1.321605,-1.473447,-0.735041,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,-0.248050,0.307747,0.526923,1.658827,0.530397,0.700949,0.628414,-1.332575,0.384010,-1.157911,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,-1.516374,-0.451373,0.767066,0.527254,-0.352589,0.540856,-1.900753,1.321605,1.349118,0.476587,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,-1.009045,1.825988,1.343410,-0.478589,-0.491344,1.010807,0.628414,1.321605,0.339452,-0.417682,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0

### Separação das variáveis de entrada e alvo

In [231]:
X = dados_processados
y = df_chamados['target_category']

In [232]:
print("Dimensão das entradas (X):", X.shape)
print("Dimensão do alvo (y):", y.shape)

Dimensão das entradas (X): (5000, 51)
Dimensão do alvo (y): (5000,)